name: gp_faucet
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  # --- UPDATED FIREBASE BRAINS ---
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  shared_preferences: ^2.5.5
  pointer_interceptor: ^0.10.1+2
  web: ^1.1.1

  url_launcher: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # 🚀 THIS IS YOUR NEW ASSETS FOLDER
  assets:
    - assets/bg.png
    - assets/logo2.png
    - assets/logo_landing.png