extend type Review {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Review", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Review`.`reviewer`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  reviewerId: UUID! @fdc_generated(from: "Review.reviewer", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Review`.`session`. It must match the value of `Session`.`id`. See `@ref` for how to customize it.
  """
  sessionId: UUID! @fdc_generated(from: "Review.session", purpose: IMPLICIT_REF_FIELD)
}
extend type Session {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Session", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Session`.`proposer`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  proposerId: UUID! @fdc_generated(from: "Session.proposer", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Session`.`recipient`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  recipientId: UUID! @fdc_generated(from: "Session.recipient", purpose: IMPLICIT_REF_FIELD)
}
extend type Skill {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Skill", purpose: IMPLICIT_KEY_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
}
extend type UserSkill {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "UserSkill", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `UserSkill`.`skill`. It must match the value of `Skill`.`id`. See `@ref` for how to customize it.
  """
  skillId: UUID! @fdc_generated(from: "UserSkill.skill", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `UserSkill`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "UserSkill.user", purpose: IMPLICIT_REF_FIELD)
}
