extend type Mutation {
  """
  ✨ Insert a single `Review` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  review_insert(
    """
    Data object to insert into the table.
    """
    data: Review_Data!
  ): Review_KeyOutput! @fdc_generated(from: "Review", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Session` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  session_insert(
    """
    Data object to insert into the table.
    """
    data: Session_Data!
  ): Session_KeyOutput! @fdc_generated(from: "Session", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Skill` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  skill_insert(
    """
    Data object to insert into the table.
    """
    data: Skill_Data!
  ): Skill_KeyOutput! @fdc_generated(from: "Skill", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `User` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insert(
    """
    Data object to insert into the table.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `UserSkill` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  userSkill_insert(
    """
    Data object to insert into the table.
    """
    data: UserSkill_Data!
  ): UserSkill_KeyOutput! @fdc_generated(from: "UserSkill", purpose: INSERT_SINGLE)
  """
  ✨ Insert `Review` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  review_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Review_Data!]!
  ): [Review_KeyOutput!]! @fdc_generated(from: "Review", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Session` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  session_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Session_Data!]!
  ): [Session_KeyOutput!]! @fdc_generated(from: "Session", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Skill` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  skill_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Skill_Data!]!
  ): [Skill_KeyOutput!]! @fdc_generated(from: "Skill", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `User` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `UserSkill` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  userSkill_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [UserSkill_Data!]!
  ): [UserSkill_KeyOutput!]! @fdc_generated(from: "UserSkill", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `Review` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Review`.
  """
  review_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Review_Data!
  ): Review_KeyOutput! @fdc_generated(from: "Review", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Session` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Session`.
  """
  session_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Session_Data!
  ): Session_KeyOutput! @fdc_generated(from: "Session", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Skill` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Skill`.
  """
  skill_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Skill_Data!
  ): Skill_KeyOutput! @fdc_generated(from: "Skill", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `User` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `UserSkill` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `UserSkill`.
  """
  userSkill_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: UserSkill_Data!
  ): UserSkill_KeyOutput! @fdc_generated(from: "UserSkill", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `Review` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Review`.
  """
  review_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Review_Data!]!
  ): [Review_KeyOutput!]! @fdc_generated(from: "Review", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Session` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Session`.
  """
  session_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Session_Data!]!
  ): [Session_KeyOutput!]! @fdc_generated(from: "Session", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Skill` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Skill`.
  """
  skill_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Skill_Data!]!
  ): [Skill_KeyOutput!]! @fdc_generated(from: "Skill", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `User` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `UserSkill` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `UserSkill`.
  """
  userSkill_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [UserSkill_Data!]!
  ): [UserSkill_KeyOutput!]! @fdc_generated(from: "UserSkill", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `Review` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Review` or `null` if not found.
  """
  review_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Review_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Review_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Review_Data!
  ): Review_KeyOutput @fdc_generated(from: "Review", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Session` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Session` or `null` if not found.
  """
  session_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Session_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Session_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Session_Data!
  ): Session_KeyOutput @fdc_generated(from: "Session", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Skill` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Skill` or `null` if not found.
  """
  skill_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Skill_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Skill_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Skill_Data!
  ): Skill_KeyOutput @fdc_generated(from: "Skill", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `User` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `User` or `null` if not found.
  """
  user_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: User_Data!
  ): User_KeyOutput @fdc_generated(from: "User", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `UserSkill` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `UserSkill` or `null` if not found.
  """
  userSkill_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: UserSkill_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserSkill_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: UserSkill_Data!
  ): UserSkill_KeyOutput @fdc_generated(from: "UserSkill", purpose: UPDATE_SINGLE)
  """
  ✨ Update `Review` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  review_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Review_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Review_Data!
  ): Int! @fdc_generated(from: "Review", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Session` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  session_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Session_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Session_Data!
  ): Int! @fdc_generated(from: "Session", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Skill` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  skill_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Skill_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Skill_Data!
  ): Int! @fdc_generated(from: "Skill", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `User` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  user_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: User_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: User_Data!
  ): Int! @fdc_generated(from: "User", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `UserSkill` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  userSkill_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: UserSkill_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: UserSkill_Data!
  ): Int! @fdc_generated(from: "UserSkill", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `Review` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  review_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Review_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Review_FirstRow
  ): Review_KeyOutput @fdc_generated(from: "Review", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Session` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  session_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Session_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Session_FirstRow
  ): Session_KeyOutput @fdc_generated(from: "Session", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Skill` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  skill_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Skill_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Skill_FirstRow
  ): Skill_KeyOutput @fdc_generated(from: "Skill", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `User` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  user_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User_KeyOutput @fdc_generated(from: "User", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `UserSkill` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  userSkill_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: UserSkill_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserSkill_FirstRow
  ): UserSkill_KeyOutput @fdc_generated(from: "UserSkill", purpose: DELETE_SINGLE)
  """
  ✨ Delete `Review` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  review_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Review_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Review", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Session` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  session_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Session_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Session", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Skill` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  skill_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Skill_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Skill", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `User` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  user_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: User_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "User", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `UserSkill` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  userSkill_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: UserSkill_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "UserSkill", purpose: DELETE_MULTIPLE)
}
